- action: setup
- when: ansible_fqdn == inventory_hostname
  block:
    - name: match hostname
      action: command hostnamectl set-hostname {{inventory_hostname}}
      become: yes
    - action: setup
