- action: setup

- when: ansible_fqdn != inventory_hostname
  name: match hostname
  command: hostnamectl set-hostname {{inventory_hostname}}
  become: yes

- when: ansible_fqdn != inventory_hostname
  action: setup
