- name: check for unwritable links
  shell: cd; test -f .{{item}} -a ! -w .{{item}} && rm -f .{{item}}
  failed_when: no
  register: check_link
  changed_when: check_link.rc <= 0
  with_items: dotfiles

- name: copy dotfiles
  template: src={{item}} dest=~/.{{item}}
  with_items: dotfiles
