- name: check for /opt
  raw: test -e /opt
  failed_when: no
  register: check_opt

- name: create /opt
  when: check_opt.rc > 0
  become: yes
  raw: mkdir -p /opt
  changed_when: yes

- name: check for pypy
  raw: test -e /opt/{{pypy_dir}}
  failed_when: no
  register: check_pypy

- name: fetch portable pypy
  when: check_pypy.rc > 0
  become: yes
  raw: curl -LfsS "{{pypy_url}}" | tar xvjC /opt
  changed_when: yes

- name: install interpreter link
  become: yes
  raw: |
    install -D /dev/null {{ansible_python_interpreter}}
    ln -fs /opt/{{pypy_dir}}/bin/pypy {{ansible_python_interpreter}}
  changed_when: yes
