---
- hosts: fedora
  vars:
    ansible_ssh_user: root
  tasks:
    - action: "{{ansible_pkg_mgr}} name=iptables-services"
    - name: mask ip6tables service file
      command: >
        systemctl mask ip6tables.service
        creates=/etc/systemd/system/ip6tables.service
    - name: override iptables service file
      synchronize:
        src: files/iptables.service
        dest: /etc/systemd/system
        rsync_opts: --chown=0:0
      notify:
        - reload systemd
        - reload iptables
    - name: copy iptables config
      synchronize:
        src: files/iptables
        dest: /etc
        delete: yes
        rsync_opts:
          - --chown=0:0
          - --chmod=o=
      notify: reload iptables
  handlers:
    - name: reload systemd
      command: systemctl daemon-reload
    - name: reload iptables
      service: name=iptables enabled=yes state=restarted
