---
- hosts: all
  tasks:
    - name: retrieve local username
      local_action: command whoami
      changed_when: no
      register: whoami
    - name: create user {{whoami.stdout}}
      user: name={{whoami.stdout}} groups=wheel
    - name: retrieve authorized keys
      local_action: shell cat files/authorized_keys
      changed_when: no
      register: ssh_keys
      failed_when: ssh_keys.stdout == ""
    - name: set authorized_keys
      authorized_key: user={{item}} exclusive=yes key={{ssh_keys.stdout}}
      with_items:
        - root
        - "{{whoami.stdout}}"
