- action: "{{ansible_pkg_mgr}} name=docker"
  notify: reload docker

- name: override docker service file
  copy: src=docker.service dest=/etc/systemd/system
  notify:
    - reload systemd
    - reload docker

- name: create docker blockdev
  shell: |
    truncate -s {{docker_btrfs_size}} {{docker_btrfs_path}}
    creates={{docker_btrfs_path}}

- action: "{{ansible_pkg_mgr}} name=btrfs-progs"

- name: format docker blockdev as btrfs
  filesystem: fstype=btrfs force=yes dev={{docker_btrfs_path}}
  notify: reload docker

- name: mount docker btrfs blockdev
  mount:
    name: /var/lib/docker
    src: /root/docker.btrfs
    fstype: btrfs
    state: mounted
  notify: reload docker
