- when: ansible_lsb is defined and ansible_lsb.id == "CoreOS"
  set_fact: docker_include=coreos

- when: docker_include is not defined
  fail: msg="unsupported system"

- include: "{{docker_include}}.yml"
